### ISSUE TITLE
全名字段用不了了

### ISSUE THREAD

**Issue by PlaneV** [windf/dokuwiki-ucenter#1]
请教大神，整合DokuWiki和UCenter、DiscuzX以后，DokuWiki的全名不可用了，变成了和用户名一样了，我需要用到全名这个字段，求大神教教我，有什么办法可以保留全名吗？谢谢！

**Comment by windf** [comment]
Hello, 你可以修改DiscuzX目录下/uc_server/control/user.php， 增加一个昵称的返回值。 再修改authuc/auth.php , _uc_user_login 的返回.   trustExternal 方法中  $user_info 数组 增加 name  ,  表示括号前的值 $_SERVER['REMOTE_USER'] 为 括号内的值 。 举个例子 $user_info["name"] = "hello"; $_SERVER['REMOTE_USER'] = "world";  则登陆名会显示  hello (world)

**Comment by PlaneV** [comment]
大神果然是大神，你太厉害了，简直就是不假思索就可以说出这么多东西，我很是佩服啊！
这个程序的语法写的太晦涩难懂了，我PHP水平又太低，估计连入门都算不上，充其量就是能读懂一般的程序，做一些小修改而已，而这个程序写的太高级了，我看的脑袋都打结了。
能不能请大神您说的更详细一些？
/uc_server/control/user.php进去看了一下，连门都没摸到，不知道到这个昵称的返回值应该增加到哪里。其实我这个用户全名可以不同步到discuzx里面的。
authuc/auth.php我也找了一圈，按照您的提示，找到了354行和580行两个关键点，但是我不知道怎么下手修改，做了一点小修改，但是没有起作用。
无奈之下，还是要再请大神帮帮我！

**Comment by windf** [comment]
已经更新test 你可以参考下, 最新的discuz x 昵称是要用插件的，具体的要自己去部署。 验证登陆后获取用户数据 $user = $_ENV['user']->get_user_by_username($username), 在 /uc_server/model/user.php 中 。你可以根据自己需要做修改

**Comment by PlaneV** [comment]
大神您好！真的很感谢您的耐心指点！我昨天太忙了，今天晚上才有时间测试。
测试发现无论用什么帐号登陆，Doku的右上角的用户信息都是“登录为: user(user)”，即使我使用您提供的test不作任何修改。
我已经按照昵称插件的要求在common_member表里面增加了nickName字段，不知道问题出在哪里了，请大神指正！

**Comment by windf** [comment]
我重新下载了 doukuwiki Version Release 2014-09-29d "Hrun" , DiscuzX 3.2  测试后没有问题。test里的uc_server/control/user.php 请确认下是否覆盖了 DiscuzX目录相应的。
